# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20171105_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
