# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=50)),
                ('paciente', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
