# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_auto_20171109_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.CharField(max_length=50),
        ),
    ]
